/**
 * @file
 *
 * Include all AST node headers.
 */

#include "tang/astNode.h"
#include "tang/astNodeArray.h"
#include "tang/astNodeAssign.h"
#include "tang/astNodeBinary.h"
#include "tang/astNodeBlock.h"
#include "tang/astNodeBoolean.h"
#include "tang/astNodeBreak.h"
#include "tang/astNodeCast.h"
#include "tang/astNodeContinue.h"
#include "tang/astNodeDoWhile.h"
#include "tang/astNodeFloat.h"
#include "tang/astNodeFor.h"
#include "tang/astNodeFunction.h"
#include "tang/astNodeFunctionCall.h"
#include "tang/astNodeIdentifier.h"
#include "tang/astNodeIfElse.h"
#include "tang/astNodeIndex.h"
#include "tang/astNodeInteger.h"
#include "tang/astNodeLibrary.h"
#include "tang/astNodeMap.h"
#include "tang/astNodeParseError.h"
#include "tang/astNodePeriod.h"
#include "tang/astNodePrint.h"
#include "tang/astNodeRangedFor.h"
#include "tang/astNodeReturn.h"
#include "tang/astNodeSlice.h"
#include "tang/astNodeString.h"
#include "tang/astNodeTernary.h"
#include "tang/astNodeUnary.h"
#include "tang/astNodeUse.h"
#include "tang/astNodeWhile.h"
